accessing
error: anError
	error := anError 